name: NoWarp
main: me.flungo.bukkit.NoWarp.NoWarp
version: 0.0.1
depend: [Residence]
description: >
              Have areas which you don't want players being able to warp in and out of? This plugin allows you to set up areas where warping will be blocked.